show_downloads: true

exclude:
  - node_modules
  - script

sass:
  style: :compressed
  
theme: jekyll-theme-midnight

github:
  is_project_page: false
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"

name: null
title: null
